# Generated by Django 5.2 on 2025-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_documentaccess_chathistory_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_id', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'external_documents',
            },
        ),
    ]
